app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// voor id's: Route::model('projects', 'App\Project');
//foor andere velden, zelf koppelen:
Route::bind('projects', function($value, $route){
   return App\Project::whereSlug($value)->first();
});

// voor id's: Route::model('tasks', 'App\Task');
//foor andere velden, zelf koppelen:
Route::bind('tasks', function($value, $route){
    return App\Task::whereSlug($value)->first();
});


Route::get('/', 'WelcomeController@index');


Route::resource('projects', 'ProjectsController');
Route::resource('projects.tasks', 'TasksController');

app/Project.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model {

	protected $fillable = ['name', 'slug'];

    public function tasks(){
        return $this->hasMany('App\Task');
    }

}

app/Task.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model {

    protected $fillable = ['name', 'slug', 'completed', 'notes', 'projct_id'];

    public function project(){
        return $this->belongsTo('App\Task');
	}

}

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

}

app/Http/Controllers/Controller.php
<?php namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesCommands;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController {

	use DispatchesCommands, ValidatesRequests;

}

app/Http/Controllers/ProjectsController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Http\Requests\SaveProjectRequest;
use App\Project;
use Illuminate\Http\Request;

class ProjectsController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$projects = Project::all();
		return view('projects.index', compact('projects'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('projects.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(SaveProjectRequest $request)
	{
		Project::create($request->all());
		return redirect()->route('projects.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($project)
	{
		return view('projects.show', compact('project'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($project)
	{
		$project->delete();
		return redirect()->route('projects.index');
	}

}

app/Http/Controllers/TasksController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class TasksController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($project, $task)
	{
		return view('tasks.show', compact('project', 'task'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/Http/Controllers/WelcomeController.php
<?php namespace App\Http\Controllers;

class WelcomeController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Welcome Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders the "marketing page" for the application and
	| is configured to only allow guests. Like most of the other sample
	| controllers, you are free to modify or remove it as you desire.
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('guest');
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('welcome');
	}

}

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo List</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1>Task Manager</h1>
    <hr/>
    @yield('content')
</div>
</body>
</html>

resources/views/projects/create.blade.php
@extends('layouts.main')

@section('content')
    <h2>Create new project</h2>
    <a href="{{ route('projects.index') }}">Back to projects</a>
    <hr/>
    {!! Form::open(['route'=>'projects.store']) !!}
    @include('projects.form', ['submittext'=>'Create new project'])
    {!! Form::close() !!}
@stop

resources/views/projects/form.blade.php
<div class="form-group">
    {!! Form::label('name') !!}
    {!! Form::text('name', null, ['class'=>'form-control']) !!}
    {!! $errors->first('name', '<p class="text-danger">:message</p>') !!}
</div>
<div class="form-group">
    {!! Form::label('slug') !!}
    {!! Form::text('slug', null, ['class'=>'form-control']) !!}
    {!! $errors->first('slug', '<p class="text-danger">:message</p>') !!}
</div>
<div class="form-group">
    {!! Form::submit($submittext, ['class'=>'btn btn-primary']) !!}
</div>

resources/views/projects/index.blade.php
@extends('layouts.main')

@section('content')
    <h2>Projects</h2>
    <a href="{{ route('projects.create') }}" class="btn btn-primary btn-sm">Create project</a>
    <hr/>
    @if($projects->count())
        <ul>
            @foreach($projects as $project)
                <li>
                    <a href="{{ route('projects.show', $project->slug) }}">
                        {{ $project->name }}
                    </a>
                    {!! Form::open(['route'=>['projects.destroy', $project->slug], 'method'=>'delete', 'style'=>'display:inline-block;']) !!}
                    {!! Form::submit('delete', ['class'=>'btn btn-danger btn-xs']) !!}
                    {!! Form::close() !!}
                </li>
            @endforeach
        </ul>
    @else
        <p>
            There were no projects found. <a href="{{ route('projects.create') }}">Add one first.</a>
        </p>
    @endif
@stop

resources/views/projects/show.blade.php
@extends('layouts.main')

@section('content')
    <h2>Project: {{ $project->name }}</h2>
    <a href="{{ route('projects.index') }}">Back to projects</a>
    <hr/>
    <h3>Tasks:</h3>
    @if ($project->tasks->count())
        <ul>
            @foreach ($project->tasks as $task)
                <li>
                    <a href="{{ route('projects.tasks.show', [$project->slug, $task->slug]) }}">{{ $task->name }}</a>
                </li>
            @endforeach
        </ul>
    @else
        <p>
            There were no tasks found.
        </p>
    @endif
@stop

resources/views/tasks/show.blade.php
@extends('layouts.main')

@section('content')
    <h2>Project: {{ $project->name }}</h2>
    <a href="{{ route('projects.show', $project->slug) }}">Back to project</a>
    <hr/>
    <h3>{{ $task->name }}</h3>
    <p>
        <strong>Completed:</strong> {{ ($task->completed) ? 'Yes':'No' }}
    </p>
    <p>
        <strong>Notes:</strong>
        {{ $task->notes }}
    </p>
@stop